@Presentation.WebAPI_HostAddress = http://localhost:5046
@ContentType = application/json

### Connect Player
POST {{Presentation.WebAPI_HostAddress}}/api/players/connect
Content-Type: {{ContentType}}

{
  "tenantId": "epic-games-123",
  "playerId": "alice-123",
  "name": "Alice"
}

###
